### ISSUE TITLE
Error on Ubuntu arm

### ISSUE THREAD

**Issue by holiq** [CryptoNodeID/ore#1]
I follow the step and got this error

![Screenshot_20240405_173915_Termux](https://github.com/CryptoNodeID/ore/assets/30729921/99684261-0745-42c4-a349-b131a40038ed)

How to fix that?

**Comment by holiq** [comment]
On installation option I choose 1

```
Current installation options:


   default host triple: aarch64-unknown-linux-gnu
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with standard installation (default - just press enter)
2) Customize installation
3) Cancel installation
>1
```

**Comment by BillyJunID** [comment]
this setup is not tested for aarch.
i ran it in x86_64 working perfectly fine.

**Comment by holiq** [comment]
I see, thanks bro
